### ISSUE TITLE
Custom numeric claims change type depending on value

### ISSUE THREAD

**Issue by andreas-lundgren-storytel** [jwtk/jjwt#180]
Depending on the value of a custom numeric claim, it may be stored as a Long or an Integer (or something else?)

This causes RequiredTypeException to be thrown depending on the received value.

```
jws.getBody().get("my_Number", Long.class) // OK if value > MAX_INT. Throws exception for values <= MAX_INT
jws.getBody().get("my_Number", Integer.class) // OK if value <= MAX_INT. Throws exception for values > MAX_INT
```

This makes it very hard to write robust code. 
Suggested solution: The first example, requesting a Long.class should not fail for smaller numbers.

**Comment by andreas-lundgren-storytel** [comment]
I just realised that this issue is fixed in `pull request #172`. Will there be a new release soon?

**Comment by AlexCzar** [comment]
I see that this is still a problem in 0.9.0, for my tokens I have to remember to always check for type and properly convert:
```kotlin
when (it) {
	is Int -> it.toLong()
	is Long -> it
	else -> throw IllegalArgumentException("Claim 'blabla' should be of type Long.")
}
```

**Comment by lhazlewood** [comment]
Closing as this was resolved a while ago via https://github.com/jwtk/jjwt/pull/172
